version: '3.4'

services:
  app:
    container_name: symfony_app
    ports:
      - 8000:80
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/app/public
    build:
      context: ./
    volumes:
      - .:/var/www/html
      - ./config/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - cache:/var/www/html/app/var/cache
      - log:/var/www/html/app/var/log

  database:
    container_name: database
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: symfony
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql

volumes:
  cache:
  log: